export interface ServiceListModel {
    KODE_SERVICE; 
    TANGGAL; 
    JAM_MASUK; 
    KODE_CUSTOMER; 
    NAMA_CUSTOMER; 
    TELP_CUSTOMER; 
    ALAMAT_CUSTOMER; 
    KOTA_CUSTOMER;
    HP_CUSTOMER; 
    KODE_PRODUK; 
    NM_BRG; MERK; 
    JNS_BRG; 
    NOMOR_SERI; 
    TANGGAL_BELI; 
    NAMA_BASS; 
    JENIS_SERVICE; 
    STATUS_PRODUK;
    KODE_PENGADUAN; 
    KELENGKAPAN; 
    BIAYA; STATUS; 
    TANGGAL_SELESAI;  
    TANGGAL_KEMBALI; 
    KODE_TEKNISI; 
    NOMOR_NOTA;
}